// This file is generated by Firebase Genkit.
// Do not edit this file as changes may be overwritten.

'use server';

/**
 * @fileOverview An AI agent that suggests alternative color palettes for a website.
 * 
 * - suggestPalette - A function that suggests alternative color palettes.
 * - SuggestPaletteInput - The input type for the suggestPalette function.
 * - SuggestPaletteOutput - The return type for the suggestPalette function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const SuggestPaletteInputSchema = z.object({
  primaryColor: z
    .string()
    .describe('The primary color of the website in hex format (e.g. #A729F0).'),
  backgroundColor: z
    .string()
    .describe('The background color of the website in hex format (e.g. #222222).'),
  accentColor: z
    .string()
    .describe('The accent color of the website in hex format (e.g. #34D1C8).'),
});
export type SuggestPaletteInput = z.infer<typeof SuggestPaletteInputSchema>;

const SuggestPaletteOutputSchema = z.object({
  palettes: z
    .array(
      z.object({
        primaryColor: z
          .string()
          .describe('A suggested primary color in hex format.'),
        backgroundColor: z
          .string()
          .describe('A suggested background color in hex format.'),
        accentColor: z
          .string()
          .describe('A suggested accent color in hex format.'),
        description: z
          .string()
          .optional()
          .describe('A short description of the color palette.'),
      })
    )
    .describe('An array of suggested color palettes.'),
});
export type SuggestPaletteOutput = z.infer<typeof SuggestPaletteOutputSchema>;

export async function suggestPalette(input: SuggestPaletteInput): Promise<SuggestPaletteOutput> {
  return suggestPaletteFlow(input);
}

const prompt = ai.definePrompt({
  name: 'suggestPalettePrompt',
  input: {schema: SuggestPaletteInputSchema},
  output: {schema: SuggestPaletteOutputSchema},
  prompt: `You are an experienced web designer with an eye for modern and appealing color palettes.

  Based on the current color scheme of a website, suggest three alternative color palettes that would be suitable for a modern portfolio website with a focus on 3D graphics and animation.

  The current color scheme is as follows:
  - Primary color: {{{primaryColor}}}
  - Background color: {{{backgroundColor}}}
  - Accent color: {{{accentColor}}}

  Consider the following when suggesting palettes:
  - The website has a dark theme with vibrant neon accents.
  - The website uses 'Space Grotesk' and 'Inter' fonts.
  - The website features a modern, asymmetrical layout.
  - The website incorporates subtle animations and 3D effects.

  Your response should be an array of three color palettes, each containing a primary color, background color, and accent color in hex format. Provide a short description of each palette.
  `,
});

const suggestPaletteFlow = ai.defineFlow(
  {
    name: 'suggestPaletteFlow',
    inputSchema: SuggestPaletteInputSchema,
    outputSchema: SuggestPaletteOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
