// This file is generated by Firebase Genkit.
// Do not edit this file as changes may be overwritten.

'use server';

/**
 * @fileOverview An AI agent that suggests alternative color palettes for a website.
 * 
 * - suggestPalette - A function that suggests alternative color palettes.
 */

import {ai} from '@/ai/genkit';
import { SuggestPaletteInputSchema, SuggestPaletteOutputSchema, type SuggestPaletteInput, type SuggestPaletteOutput } from '@/lib/schemas';


export async function suggestPalette(input: SuggestPaletteInput): Promise<SuggestPaletteOutput> {
  return suggestPaletteFlow(input);
}

const prompt = ai.definePrompt({
  name: 'suggestPalettePrompt',
  input: {schema: SuggestPaletteInputSchema},
  output: {schema: SuggestPaletteOutputSchema},
  prompt: `You are an expert UI/UX designer and color theorist specializing in creating beautiful, harmonious, and accessible two-color palettes for modern web applications.

Your task is to suggest three alternative two-color palettes based on the user's current colors. The palettes should be suitable for a high-end, professional portfolio for an AI developer. One of these palettes **must** be a "Cyberpunk" theme.

**Key Principles to Follow:**

1.  **Harmony & Contrast:** The two colors in each palette must work well together. This is critical. Ensure there is sufficient contrast between the background color and the primary color for accessibility and readability. The colors should not clash.
2.  **Professionalism & Personality:** The palettes should feel modern and sophisticated, but also have character. They should be appropriate for a technology professional's portfolio.
3.  **Cyberpunk Palette:** For the Cyberpunk theme, think high-contrast, a vibrant neon (like electric green, cyan, or magenta) against a very dark, deep background. This palette should feel futuristic, edgy, and digital.

**User's Current Palette:**
- Primary: {{{primaryColor}}}
- Background: {{{backgroundColor}}}

**Your Task:**
Generate three distinct and professional two-color palettes. For each, provide a primary color and a background color in hex format, and a short, descriptive name. Ensure the palettes are harmonious and follow the principles above.

**Example Palette Names:**
- "Cyberpunk Neon"
- "Modern Professional"
- "Deep Ocean"
- "Vibrant Tech"
`,
});

const suggestPaletteFlow = ai.defineFlow(
  {
    name: 'suggestPaletteFlow',
    inputSchema: SuggestPaletteInputSchema,
    outputSchema: SuggestPaletteOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
